import type { ImgHTMLAttributes } from 'react';
import type { CmsImage as Img } from '@/lib/media';

type Props = Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'> & {
  src: Img | string;
  alt?: string;
};

/**
 * Renders an image uploaded to the CMS. Payload already generated the resized variants,
 * so this emits a plain <img srcset> instead of re-optimising them with next/image.
 */
export function CmsImage({
  src,
  alt,
  width,
  height,
  sizes,
  loading = 'lazy',
  decoding = 'async',
  ...rest
}: Props) {
  const img: Img = typeof src === 'string' ? { src } : src;

  // Keep the intrinsic aspect ratio when only one dimension is pinned.
  const ratio = img.width && img.height ? img.height / img.width : undefined;
  const w = width
    ? Number(width)
    : height && ratio
      ? Math.round(Number(height) / ratio)
      : img.width;
  const h = height
    ? Number(height)
    : width && ratio
      ? Math.round(Number(width) * ratio)
      : img.height;

  return (
    // biome-ignore lint/performance/noImgElement: sizes are pre-generated by Payload
    <img
      src={img.src}
      srcSet={img.srcset}
      sizes={
        sizes ??
        (img.srcset
          ? w
            ? `(max-width: ${w}px) 100vw, ${w}px`
            : '100vw'
          : undefined)
      }
      alt={alt ?? img.alt ?? ''}
      width={w}
      height={h}
      loading={loading}
      decoding={decoding}
      {...rest}
    />
  );
}
